-- Yokohama Tires - Snowflake Intelligence Demo
-- 00_setup.sql: Warehouses, roles, database, schemas, and grants
-- Safe to rerun; uses IF NOT EXISTS where possible

-- Parameters (edit if desired)
SET ROLE_NAME = 'YOKO_DEMO_ROLE';
SET WH_NAME   = 'YOKO_DEMO_WH';
SET DB_NAME   = 'YOKO_DEMO_DB';
SET SCH_CORE  = 'CORE';
SET SCH_SEM   = 'SEMANTICS';

-- Create role (skip if not allowed; run as SECURITYADMIN or ACCOUNTADMIN)
CREATE ROLE IF NOT EXISTS IDENTIFIER($ROLE_NAME);

-- Grant basic privileges to role
GRANT USAGE ON INTEGRATION ALL TO ROLE IDENTIFIER($ROLE_NAME);
-- Note: The above line may be ignored if you lack privileges; safe to proceed.

-- Create warehouse (requires ACCOUNTADMIN or similar)
CREATE WAREHOUSE IF NOT EXISTS IDENTIFIER($WH_NAME)
  WAREHOUSE_SIZE = 'XSMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = TRUE
  COMMENT = 'Warehouse for Yokohama demo';

GRANT USAGE, OPERATE ON WAREHOUSE IDENTIFIER($WH_NAME) TO ROLE IDENTIFIER($ROLE_NAME);

-- Create database and schemas
CREATE DATABASE IF NOT EXISTS IDENTIFIER($DB_NAME) COMMENT='Yokohama Tires demo database';
GRANT OWNERSHIP ON DATABASE IDENTIFIER($DB_NAME) TO ROLE IDENTIFIER($ROLE_NAME) COPY CURRENT GRANTS;

USE DATABASE IDENTIFIER($DB_NAME);

CREATE SCHEMA IF NOT EXISTS IDENTIFIER($SCH_CORE);
CREATE SCHEMA IF NOT EXISTS IDENTIFIER($SCH_SEM);

GRANT USAGE ON DATABASE IDENTIFIER($DB_NAME) TO ROLE IDENTIFIER($ROLE_NAME);
GRANT USAGE ON ALL SCHEMAS IN DATABASE IDENTIFIER($DB_NAME) TO ROLE IDENTIFIER($ROLE_NAME);
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE IDENTIFIER($DB_NAME) TO ROLE IDENTIFIER($ROLE_NAME);

-- Default session role and warehouse (adjust if needed)
USE ROLE IDENTIFIER($ROLE_NAME);
USE WAREHOUSE IDENTIFIER($WH_NAME);
USE SCHEMA IDENTIFIER($DB_NAME)||'.'||IDENTIFIER($SCH_CORE);

-- Confirm context
SELECT CURRENT_ROLE(), CURRENT_WAREHOUSE(), CURRENT_DATABASE(), CURRENT_SCHEMA();


